export const admin_page: string;
export const input_file: string;
export const input_file_text: string;
export const input_file_btn: string;
export const label_title: string;
export const active_tab: string;
export const wrapper_feedbacks: string;
export const feedback: string;
export const buttons: string;